title: 

logo: /assets/img/headshot.png

description: <a href="mailto:a.j.wilson1@leeds.ac.uk">✉️ a.j.wilson1@leeds.ac.uk</a> <br/>
             <a href="https://scholar.google.co.uk/citations?hl=en&user=POyerY0AAAAJ&view_op=list_works&sortby=pubdate">🎓 Google Scholar </a> <br/>
             <a href="https://fwilson93.github.io/Portfolio/assets/AJWS_CV.pdf">📃 CV </a>  <br/>
             
show_downloads: false

google_analytics:

theme: jekyll-theme-minimal
