title: Alfred<br/>Wilson-Spencer

logo: /assets/img/SEDI_side_profile.jpg

description: I am a research fellow at the University of Leeds studying the thermochemical evolution of Earth’s core. <br/>
             <br/>
             <a href="mailto:a.j.wilson1@leeds.ac.uk">✉️ a.j.wilson1@leeds.ac.uk</a> <br/>
             <a href="https://scholar.google.co.uk/citations?hl=en&user=POyerY0AAAAJ&view_op=list_works&sortby=pubdate">🎓 Google Scholar </a> <br/>
             <a href="https://fwilson93.github.io/Portfolio/assets/AJWS_CV.pdf">📃 CV </a>  <br/>
             📍 Leeds, UK <br/><br/>

             <a href="https://www.minersoc.org/mpg.html">Chair of the Mineral Physics Special Interest Group of the Mineralogical Society
of the UK and Ireland</a> <br/>
             <a href="https://hope.simons-rock.edu/~bergman/sedi/doornbos.html">🥇 Doornbos Awardee 2024</a> <br/>
             
show_downloads: false

google_analytics: true

theme: jekyll-theme-minimal
