title: Alfred Wilson-Spencer
logo: /assets/img/headshot.png
description: description: <a href="http://www.google.com">Testing Landing Page</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
