title: Alfred Wilson-Spencer
logo: /assets/img/headshot.png
description: <a href="https://scholar.google.co.uk/citations?hl=en&user=POyerY0AAAAJ&view_op=list_works&sortby=pubdate">🎓 LinkedIn</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
